#![allow(clippy::too_many_arguments, clippy::new_without_default, non_camel_case_types, unused_imports)]
/*
 * IoEngine RESTful API
 *
 * The version of the OpenAPI document: v0
 *
 * Generated by: https://github.com/openebs/openapi-generator
 */

use crate::apis::{IntoOptVec, IntoVec};




/// ReplicaUsage : Replica space usage information. Useful for capacity management, eg: figure out how much of a thin-provisioned replica is allocated. 









/// Replica space usage information. Useful for capacity management, eg: figure out how much of a thin-provisioned replica is allocated. 
#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub struct ReplicaUsage {

    
    /// Replica capacity in bytes.
    #[serde(rename = "capacity")]
    pub capacity: u64,

    
    /// Amount of actually allocated disk space for this replica in bytes.
    #[serde(rename = "allocated")]
    pub allocated: u64,

}

impl ReplicaUsage {
    /// ReplicaUsage using only the required fields
    pub fn new(capacity: impl Into<u64>, allocated: impl Into<u64>) -> ReplicaUsage {
        ReplicaUsage {
            
            capacity: capacity.into(),
            
            allocated: allocated.into(),
            
        }
    }
    /// ReplicaUsage using all fields
    pub fn new_all(capacity: impl Into<u64>, allocated: impl Into<u64>) -> ReplicaUsage {
        ReplicaUsage {
            
            capacity: capacity.into(),
            
            allocated: allocated.into(),
            
        }
    }
}












