#![allow(clippy::too_many_arguments, clippy::new_without_default, non_camel_case_types, unused_imports)]
/*
 * IoEngine RESTful API
 *
 * The version of the OpenAPI document: v0
 *
 * Generated by: https://github.com/openebs/openapi-generator
 */

use crate::apis::{IntoOptVec, IntoVec};




/// VolumeSnapshots : Array of volume snapshots.









/// Array of volume snapshots.
#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub struct VolumeSnapshots {

    
    #[serde(rename = "entries")]
    pub entries: Vec<crate::models::VolumeSnapshot>,

}

impl VolumeSnapshots {
    /// VolumeSnapshots using only the required fields
    pub fn new(entries: impl IntoVec<crate::models::VolumeSnapshot>) -> VolumeSnapshots {
        VolumeSnapshots {
            
            entries: entries.into_vec(),
            
        }
    }
    /// VolumeSnapshots using all fields
    pub fn new_all(entries: impl IntoVec<crate::models::VolumeSnapshot>) -> VolumeSnapshots {
        VolumeSnapshots {
            
            entries: entries.into_vec(),
            
        }
    }
}










