#![allow(clippy::too_many_arguments, clippy::new_without_default, non_camel_case_types, unused_imports)]
/*
 * IoEngine RESTful API
 *
 * The version of the OpenAPI document: v0
 *
 * Generated by: https://github.com/openebs/openapi-generator
 */

use crate::apis::{IntoOptVec, IntoVec};




/// VolumeSpec : User specification of a volume.









/// User specification of a volume.
#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub struct VolumeSpec {

    
    /// Optionally used to store custom volume information
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<::std::collections::HashMap<String, String>>,

    
    /// Number of children the volume should have.
    #[serde(rename = "num_replicas")]
    pub num_replicas: u8,

    
    /// Record of the operation in progress
    #[serde(rename = "operation", skip_serializing_if = "Option::is_none")]
    pub operation: Option<crate::models::VolumeSpecOperation>,

    
    /// Size that the volume should be.
    #[serde(rename = "size")]
    pub size: u64,

    
    /// Common base state for a resource
    #[serde(rename = "status")]
    pub status: crate::models::SpecStatus,

    
    /// Specification of a volume target
    #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
    pub target: Option<crate::models::VolumeTarget>,

    
    /// Volume Id
    #[serde(rename = "uuid")]
    pub uuid: uuid::Uuid,

    
    /// node and pool topology for volumes
    #[serde(rename = "topology", skip_serializing_if = "Option::is_none")]
    pub topology: Option<crate::models::Topology>,

    
    /// Volume policy used to determine if and how to replace a replica
    #[serde(rename = "policy")]
    pub policy: crate::models::VolumePolicy,

    
    /// Thin provisioning flag
    #[serde(rename = "thin")]
    pub thin: bool,

    
    /// Affinity Group related information.
    #[serde(rename = "affinity_group", skip_serializing_if = "Option::is_none")]
    pub affinity_group: Option<crate::models::AffinityGroup>,

}

impl VolumeSpec {
    /// VolumeSpec using only the required fields
    pub fn new(num_replicas: impl Into<u8>, size: impl Into<u64>, status: impl Into<crate::models::SpecStatus>, uuid: impl Into<uuid::Uuid>, policy: impl Into<crate::models::VolumePolicy>, thin: impl Into<bool>) -> VolumeSpec {
        VolumeSpec {
            
            labels: None,
            
            num_replicas: num_replicas.into(),
            
            operation: None,
            
            size: size.into(),
            
            status: status.into(),
            
            target: None,
            
            uuid: uuid.into(),
            
            topology: None,
            
            policy: policy.into(),
            
            thin: thin.into(),
            
            affinity_group: None,
            
        }
    }
    /// VolumeSpec using all fields
    pub fn new_all(labels: impl Into<Option<::std::collections::HashMap<String, String>>>, num_replicas: impl Into<u8>, operation: impl Into<Option<crate::models::VolumeSpecOperation>>, size: impl Into<u64>, status: impl Into<crate::models::SpecStatus>, target: impl Into<Option<crate::models::VolumeTarget>>, uuid: impl Into<uuid::Uuid>, topology: impl Into<Option<crate::models::Topology>>, policy: impl Into<crate::models::VolumePolicy>, thin: impl Into<bool>, affinity_group: impl Into<Option<crate::models::AffinityGroup>>) -> VolumeSpec {
        VolumeSpec {
            
            labels: labels.into(),
            
            num_replicas: num_replicas.into(),
            
            operation: operation.into(),
            
            size: size.into(),
            
            status: status.into(),
            
            target: target.into(),
            
            uuid: uuid.into(),
            
            topology: topology.into(),
            
            policy: policy.into(),
            
            thin: thin.into(),
            
            affinity_group: affinity_group.into(),
            
        }
    }
}






























