#![allow(clippy::too_many_arguments, clippy::new_without_default, non_camel_case_types, unused_imports)]
/*
 * IoEngine RESTful API
 *
 * The version of the OpenAPI document: v0
 *
 * Generated by: https://github.com/openebs/openapi-generator
 */

use crate::apis::{IntoOptVec, IntoVec};




/// VolumeSnapshotDefinition : Volume Snapshot Metadata and Spec information.









/// Volume Snapshot Metadata and Spec information.
#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize, Deserialize)]
pub struct VolumeSnapshotDefinition {

    
    /// Volume Snapshot Metadata information.
    #[serde(rename = "metadata")]
    pub metadata: crate::models::VolumeSnapshotMetadata,

    
    /// Volume Snapshot Spec information.
    #[serde(rename = "spec")]
    pub spec: crate::models::VolumeSnapshotSpec,

}

impl VolumeSnapshotDefinition {
    /// VolumeSnapshotDefinition using only the required fields
    pub fn new(metadata: impl Into<crate::models::VolumeSnapshotMetadata>, spec: impl Into<crate::models::VolumeSnapshotSpec>) -> VolumeSnapshotDefinition {
        VolumeSnapshotDefinition {
            
            metadata: metadata.into(),
            
            spec: spec.into(),
            
        }
    }
    /// VolumeSnapshotDefinition using all fields
    pub fn new_all(metadata: impl Into<crate::models::VolumeSnapshotMetadata>, spec: impl Into<crate::models::VolumeSnapshotSpec>) -> VolumeSnapshotDefinition {
        VolumeSnapshotDefinition {
            
            metadata: metadata.into(),
            
            spec: spec.into(),
            
        }
    }
}












